package com.app.preorder.common.type;

public enum OrderStatus {
    ORDER_COMPLETE, PREPARING_DELIVERY, ORDER_CANCEL, DELIVERYING, DELIVERY_COMPLETE, RETURN_NOT_PERMITTED, RETURNING, RETURN_COMPLETE
}
