spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://mariadb:3306/preorder}
    username: ${SPRING_DATASOURCE_USERNAME:taek}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: authPool                    # ⬅️ 풀 이름 고정
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:6}   # ⬅️ 보조: MAX 6
      minimum-idle: ${HIKARI_MIN_IDLE:0}             # ⬅️ idle 0 (DB 슬롯 절약)
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 64
          max-idle: 16
          min-idle: 8
          time-between-eviction-runs: 60s

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: false
    properties:
      hibernate.default_batch_fetch_size: 100

server:
  port: 8081
  tomcat:
    threads:
      max: 150
    accept-count: 1000
    connection-timeout: 10000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:Pr5aQ!9zdT7XgW2mXyCb$$Hr4LdS6kJvB}

email:
  auto-verify: ${EMAIL_AUTO_VERIFY:false}

feign:
  client:
    config:
      member-service:
        connectTimeout: 1500
        readTimeout: 3000
        loggerLevel: basic
        retryer: feign.Retryer$NeverRetry

logging:
  level:
    root: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.cloud: WARN

# (필수) actuator 메트릭 노출
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
