spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mariadb://localhost:3307/preorder
    username: taek
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: Pr5aQ!9zdT7XgW2mXyCb$$Hr4LdS6kJvB

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/