version: '3.7'

services:
  mariadb:
    container_name: docker-mariadb
    image: mariadb:10.5.5
    init: true
    user: root
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/config:/etc/mysql/conf.d
    ports:
      - 3307:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3307
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: preorder
      MYSQL_USER: taek
      MYSQL_PASSWORD: 1234

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
