package com.app.preorder.common.type;

public enum OrderStatus {
    PAYMENT_PREPARING, PAYMENT_PROCESSING, ORDER_COMPLETE, DELIVERY_PREPARING, ORDER_CANCEL, DELIVERYING, DELIVERY_COMPLETE, RETURN_NOT_PERMITTED, RETURNING, RETURN_COMPLETE
}
