spring:
  application:
    name: member-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://mariadb:3306/preorder}
    username: ${SPRING_DATASOURCE_USERNAME:taek}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:50}
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:uitaek98@gmail.com}
    password: ${MAIL_PASSWORD:fgto sxpl wlue pezq}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
    admin:
      fail-fast: false

jwt:
  secret: ${JWT_SECRET:Pr5aQ!9zdT7XgW2mXyCb$$Hr4LdS6kJvB}

aes:
  key: ${AES_KEY:0123456789abcdef0123456789abcdef}
  salt: ${AES_SALT:abcdefabcdefabcdefabcdefabcdefab}

hmac:
  secret-key: ${HMAC_SECRET_KEY:Dh8tS$$3uLw5ZxP2kQy9VgR7fNj1TbV0a}

server:
  port: 8082

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discovery-service:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

email:
  auto-verify: ${EMAIL_AUTO_VERIFY:false}

feign:
  client:
    config:
      auth-service:
        connectTimeout: 500
        readTimeout: 800
        loggerLevel: none
        retryer: feign.Retryer$NeverRetry