spring:
  application:
    name: member-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://mariadb:3306/preorder}
    username: ${SPRING_DATASOURCE_USERNAME:taek}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: memberPool                          # ⬅️ 풀 이름
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:6}   # ⬅️ 보조: MAX 6
      minimum-idle: ${HIKARI_MIN_IDLE:0}             # ⬅️ idle 0
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 64
          max-idle: 16
          min-idle: 8
          time-between-eviction-runs: 60s

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate.default_batch_fetch_size: 100

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:uitaek98@gmail.com}
    password: ${MAIL_PASSWORD:fgto sxpl wlue pezq}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
    admin:
      fail-fast: false

server:
  port: 8082
  tomcat:
    threads:
      max: 200
    accept-count: 1000
    connection-timeout: 10000

jwt:
  secret: ${JWT_SECRET:Pr5aQ!9zdT7XgW2mXyCb$$Hr4LdS6kJvB}

aes:
  key: ${AES_KEY:0123456789abcdef0123456789abcdef}
  salt: ${AES_SALT:abcdefabcdefabcdefabcdefabcdefab}

hmac:
  secret-key: ${HMAC_SECRET_KEY:Dh8tS$$3uLw5ZxP2kQy9VgR7fNj1TbV0a}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

email:
  auto-verify: ${EMAIL_AUTO_VERIFY:false}

feign:
  client:
    config:
      auth-service:
        connectTimeout: 1000
        readTimeout: 1800
        loggerLevel: none
        retryer: feign.Retryer$NeverRetry

logging:
  level:
    root: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
