spring:
  application:
    name: member-service

  datasource:
    url: jdbc:mariadb://localhost:3307/preorder
    username: taek
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: uitaek98@gmail.com
    password: fgto sxpl wlue pezq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

aes:
  key: U2Yz6Nw8sR2yPv5VtG4bYq9ZtL1xAe7Q
  salt: a9W3vC1eZ6rM2bT7

hmac:
  secret-key: Dh8tS$3uLw5ZxP2kQy9VgR7fNj1TbV0a

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/