server:
  port: 8761
  tomcat:
    threads:
      max: 100        # Eureka 대규모 트래픽 받지 않으므로 과하지 않게
    accept-count: 500
    connection-timeout: 10000

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false   # 서버 자신은 등록/조회 안 함
    fetch-registry: false
  server:
    # ✅ 자기보호 모드는 유지(대형 테스트 중에도 과민 반응 방지)
    enable-self-preservation: true
    # 허용 임계치 (기본 0.85). 과도한 샤딩/재배포 시 false-evict 방지
    renewal-percent-threshold: 0.85

    # ✅ Eviction/캐시 튜닝
    eviction-interval-timer-in-ms: 10000            # 10초마다 만료 인스턴스 정리(기본 60초)
    response-cache-update-interval-ms: 5000         # 응답 캐시 업데이트 주기
    response-cache-auto-expiration-in-seconds: 30   # 응답 캐시 TTL
    use-read-only-response-cache: true              # 읽기 전용 캐시 사용(락 경합 감소)

logging:
  level:
    root: WARN
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN

# ★ 액추에이터/프로메테우스(최소)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
