spring:
  application:
    name: order-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://mariadb:3306/preorder}
    username: ${SPRING_DATASOURCE_USERNAME:taek}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: orderPool
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:15}
      minimum-idle: ${HIKARI_MIN_IDLE:2}
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 96
          max-idle: 24
          min-idle: 8
          time-between-eviction-runs: 60s

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate.default_batch_fetch_size: 100

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    listener:
      missing-topics-fatal: false
    producer:
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
    consumer:
      properties:
        spring.json.use.type.headers: false

server:
  port: 8084
  tomcat:
    threads:
      max: 200
    accept-count: 1000
    connection-timeout: 10000

jwt:
  secret: ${JWT_SECRET:Pr5aQ!9zdT7XgW2mXyCb$$Hr4LdS6kJvB}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

email:
  auto-verify: ${EMAIL_AUTO_VERIFY:false}

feign:
  client:
    config:
      product-service:
        connectTimeout: 1200
        readTimeout: 2000
        loggerLevel: none
        retryer: feign.Retryer$NeverRetry

resilience4j:
  circuitbreaker:
    instances:
      productClient:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 1s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - io.netty.channel.ConnectTimeoutException
          - feign.RetryableException

logging:
  level:
    root: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
    feign: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

order:
  expiration:
    sweep-interval-ms: 10000
    batch-size: 300
    grace-seconds: 10
    max-rounds: 10

kafka:
  consumer:
    stock-result:
      concurrency: 6
