spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mariadb://localhost:3307/preorder
    username: taek
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/