spring:
  application:
    name: product-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://mariadb:3306/preorder}
    username: ${SPRING_DATASOURCE_USERNAME:taek}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: productPool
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:40}
      minimum-idle: ${HIKARI_MIN_IDLE:10}
      idle-timeout: 30000
      max-lifetime: 1700000     # ★ 1800000 → 1700000
      connection-timeout: 2000  # ★ 30000 → 2000

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 128
          max-idle: 32
          min-idle: 8
          time-between-eviction-runs: 60s

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate.default_batch_fetch_size: 100

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    listener:
      missing-topics-fatal: false
    # ★ Producer 성능 모드
    producer:
      acks: 1
      linger-ms: 10
      batch-size: 65536
      compression-type: lz4
      properties:
        enable.idempotence: false
        spring.json.add.type.headers: false
    consumer:
      properties:
        spring.json.use.type.headers: false

server:
  port: 8085
  tomcat:
    threads:
      max: 200
    accept-count: 1000
    connection-timeout: 10000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:Pr5aQ!9zdT7XgW2mXyCb$$Hr4LdS6kJvB}

email:
  auto-verify: ${EMAIL_AUTO_VERIFY:false}

kafka:
  consumer:
    command:
      concurrency: 6
    event:
      concurrency: 6

# ★ Product Inbox 처리 주기 (기본 700ms → 200ms로 단축)
inbox:
  product:
    process-interval-ms: 200

logging:
  level:
    root: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
