spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mariadb://localhost:3307/preorder
    username: taek
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/